### ISSUE TITLE
Extension doesn't work with VSCode 1.29.1

### ISSUE THREAD

**Issue by Tobiyashi** [x10sv/pml#2]
Hi,
we use Visual Studio Code 1.29.1 at work and i have no control over updates or anything.

Unfortunately when i try to install the extension the following error message appears:
"Unable to install because, the extension 'angelincalu.pml'
compatible with current version '1.29.1' of VS Code is not found.
![image](https://user-images.githubusercontent.com/49440579/56196849-eef4d000-6037-11e9-8987-6c85cc57aa81.png)

**Comment by AngelinCalu** [comment]
Minimum `vscode` version updated to `^1.21.1`. 

I will find time in the future to check with older versions as well. (For sure in `v1.13.1` it does not work)

**Comment by Tobiyashi** [comment]
Thanks for the fast reply and change. Works like a charm.
