### ISSUE TITLE
.mac == .pmlmac

### ISSUE THREAD

**Issue by DemnDev** [x10sv/pml#5]
hi,
Where I work they use the ".mac" extension for Macro is it the same as ".pmlmac" ?
can you make it accepte extension ".mac" ? this will be very appreciate :)
you make a very good job !

thanks :)

**Comment by AngelinCalu** [comment]
Will add it later today. Thanks for the proposal.

**Comment by AngelinCalu** [comment]
This was now added in version `0.1.14`. Closing this.

**Comment by DemnDev** [comment]
thank a lot :)
